### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by tojeteter** [gaochao-s/ope-sr#3]
I encountered an "OutOfMemoryError" while running my code in Google Colab, and I'm unsure whether it's due to an issue with the code or if I need more memory in my hardware.I used RDN-OPE weights from google drive.I also encountered the same problem when using a remote machine with a 2080ti GPU and when running the code on a CPU with 16GB of RAM.
`import torch
from models import make
import dl_utils
from test import single_img_sr
import torch.nn.functional as F

sv_file = torch.load('epoch-1000.pth')
model = make(sv_file['model'], load_sd=True).cuda()

img_hr = dl_utils.load_imageToten('test_imgs/0803.png').cuda()
h,w = img_hr.shape[2:]

img_lr = F.interpolate(img_hr, size=(768,1020), mode='bilinear', align_corners=False).cuda()
sr_img, psnr_model, ssim_model, run_time = single_img_sr(img_lr, model, h=h, w=w, gt=img_hr)`

**OutOfMemoryError                          Traceback (most recent call last)

[<ipython-input-14-ea0aedd07168>](https://localhost:8080/#) in <cell line: 1>()
----> 1 sr_img, psnr_model, ssim_model, run_time = single_img_sr(img_lr, model, h=h, w=w, gt=img_hr)

3 frames

[/content/ope-sr/models/rdn.py](https://localhost:8080/#) in forward(self, x)
    121             RDBs_out.append(x)
    122 
--> 123         x = self.GFF(torch.cat(RDBs_out, 1))
    124         x += f__1
    125 

OutOfMemoryError: CUDA out of memory. Tried to allocate 6.87 GiB (GPU 0; 14.75 GiB total capacity; 7.78 GiB already allocated; 3.12 GiB free; 10.62 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF**

**Comment by gaochao-s** [comment]
You can just run ope_demo_zoom.py as shown in README, which has no problem on 3090. Typically OOM occures when input resolution is fairly high as RDN network occupies the most of the memory. For compromise, you can set "--scale_list" to 6+ to guarentee relatively low resolution input on the device with small memory.
